=== WeBankBlockchain/WeIdentity/src/test/resources/test-singlelevel-cpt.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "five information requirements for users",
    "title": "身份证",
    "type": "object",
    "properties": {
        "weid": {
            "type": "string",
            "name": "微ID",
            "description": "user weId"
        },
        "age": {
            "description": "the age of certificate owner",
            "type": "integer",
            "name": "年龄"
        },
        "gender": {
            "description": "the gender of certificate owner",
            "enum": [
                "F",
                "M"
            ],
            "type": "string",
            "name": "性别"
        },
        "name": {
            "description": "the name of certificate owner",
            "type": "string",
            "name": "名字"
        }
    },
    "required": [
        "name",
        "age"
    ]
}

=== WeBankBlockchain/WeIdentity/src/test/resources/testSingleLevelClaim.json
{
  "weid": "did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7",
  "name": "did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7did:weid:101:0xce618fb7fbacaf6398a0b4b78bf2dd942c8c49c7",
  "gender": "M",
  "age":26
}
